"use client"

import Navbar from '../Components/Clientside/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { TodosProvider } from '@/Components/Clientside/TodoProvider'
import { AuthProvider } from '@/Components/Clientside/authProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <AuthProvider>

            <TodosProvider>
              {/* <Navbar /> */}
              {children}
            </TodosProvider>
          </AuthProvider>
        </>
      </body>
    </html>
  )
}
